name: Test pype

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Pype
        run: |
          sh setup.sh
          source ~/.pype_profile
          pype requests
          echo $?

      - name: Lint with flake8
        run: |
           # stop the build if there are Python syntax errors or undefined names
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # exit-zero treats all errors as warnings.
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#      - name: Test Pype
#        run: |
#          if ! sh setup.sh; then
#            echo 1. Setup script run correctly: Fail
#          else
#            echo 1. Setup script run correctly: Pass
#          fi
#
#      - name: Test Pype
#        run: |
#          result_not=$(pype request; echo $?)
#          result=$(pype requests; echo $?)
#
#          if [[ result_not -eq 1 ]]
#          then
#            echo 2. Returns exit code 1 on not found: Pass
#          else
#            echo 2. Returns exit code 1 on not found: Fail
#          fi
#
#          if [[ result -eq 0  ]]
#          then
#            echo 3. Returns exit code 0 on found: Pass
#          else
#            echo 3. Returns exit code 0 on found: Fail
#          fi